### PR TITLE
Fixes for react/reply buddy aliases and embed/image display, show call/join messages

### LINKED ISSUE #347: Links in embeds are not displayed
At times a message's content will consist solely of URLs inside embeds (a notable example is messages generated by bots/webhooks).

The plugin currently ignores such URLs, displaying an empty embed.

See https://discord.com/developers/docs/resources/channel#embed-object for additional info.

The relevant tags inside embeds are `url`, `video`, `image`, `thumbnail`

For example:
```
{
  "id": "...",
  "type": 0,
  "content": "",
  "channel_id": "...",
  "author": { ... },
  "attachments": [],
  "embeds": [
    {
      "type": "rich",
      "title": "Meow 😻",
      "image": {
        "url": "https://cdn.weeb.sh/images/SkgJ54VYG.jpeg",
        "proxy_url": "https://images-ext-1.discordapp.net/external/-615p33LtpnLL7FmaPhFQlNVtoqaNhOQIqIekkmMHak/https/cdn.weeb.sh/images/SkgJ54VYG.jpeg",
        "width": 2390,
        "height": 4250
      },
      "footer": { "text": "powered by weebs (weeb.sh)" }
    }
  ],
  "mentions": [],
  "mention_roles": [],
  "pinned": false,
  "mention_everyone": false,
  "tts": false,
  "timestamp": "...",
  "edited_timestamp": null,
  "flags": 0,
  "components": []
},
```

### PR DESCRIPTION
**Pull request by dlmarquis**
Should fix #347 and #345.

I also caught some mistakes I made in my image handling code from a previous PR. This caused messages to not display under some mysterious circumstances.

As a bonus, I added handling for call messages and guild member join messages, which previously could cause a blank chat window to open with no context as to why.

As always, let me know if you want these split out into separate PRs.

### CODE REVIEW

File: libdiscord.c [hunk 1]
```diff
@@ -2368,21 +2418,25 @@ discord_process_message(DiscordAccount *da, JsonObject *data, unsigned special_t
 
 					PurpleChatConversation *chatconv = purple_conversations_find_chat(da->pc, discord_chat_hash(channel_id));
  					conv = PURPLE_CONVERSATION(chatconv);
-					
+
 					if (conv != NULL) {
 						int head_count = guild ? g_hash_table_size(guild->members) : 0;
-						if (head_count > 0 && (head_count < purple_account_get_int(da->account, "large-channel-count", 20) || purple_account_get_bool(da->account, "display-images-large-servers", FALSE) )) {
+						if (head_count < purple_account_get_int(da->account, "large-channel-count", 20) || purple_account_get_bool(da->account, "display-images-large-servers", FALSE) ) {
```
Comment (dlmarquis) [inline libdiscord.c:2424]: I removed the `head_count > 0` statement because I was getting invalid values for it in one of my servers (possibly because the whole server is nsfw?). However, I'm no longer seeing that, so I'm not sure what caused it.

File: libdiscord.c [hunk 2]
```diff
@@ -2368,21 +2418,25 @@ discord_process_message(DiscordAccount *da, JsonObject *data, unsigned special_t
...
 							discord_fetch_url(da, img_context->url, NULL, discord_download_image_cb, img_context);
 							GList *l = conv->logs;
 							if (l != NULL) {
 								PurpleLog *log = l->data;
 								purple_log_write(log, flags | PURPLE_MESSAGE_INVISIBLE, name, timestamp, url_log);
 							}
+						} else {
+							purple_serv_got_chat_in(da->pc, discord_chat_hash(channel_id), name, flags, url_log, timestamp);
 						}
+					} else {
```
Comment (dlmarquis) [inline libdiscord.c:2434]: I was also getting messages trapped here, where `conv == NULL`, for completely unknown reasons since we've attempted to grab the chatconv twice at this point.

File: libdiscord.c [hunk 3]
```diff
@@ -2115,7 +2130,21 @@ discord_process_message(DiscordAccount *da, JsonObject *data, unsigned special_t
 					}
 				}
 			}
-			// image - TODO
+
+			if (image != NULL && json_object_has_member(image, "url")) {
```
Comment (dlmarquis) [inline libdiscord.c:2134]: TODO: Handle image embeds the way image attachments are done

Comment (EionRobb) [reply libdiscord.c:2134]: Did you want to finish this TODO before merging, or after?

File: libdiscord.c [hunk 4]
```diff
@@ -3500,6 +3554,9 @@ discord_process_dispatch(DiscordAccount *da, const gchar *type, JsonObject *data
 				user_nick = _("You");
 			} else {
 				user_nick = username;
+				PurpleBuddy *buddy = purple_blist_find_buddy(da->account, user_nick);
+				if (buddy != NULL)
+					user_nick = purple_buddy_get_alias(buddy);
```
Comment (EionRobb) [inline libdiscord.c:3559]: Is it worth splitting this 'get display name of user' code into a separate function, since it's used 3 or 4 places through this PR?  Happy for it to be a separate PR if you want

File: libdiscord.c (hunk 3 above)
Comment (dlmarquis) [reply libdiscord.c:2134]: I'm going to be busy until the end of the month, so it's probably best to merge this now, and I'll get to this later on.

File: libdiscord.c (hunk 4 above)
Comment (dlmarquis) [reply libdiscord.c:3559]: It probably is, but I can do it in a separate PR
