### PR TITLE
Fix direct message ack'ing

### LINKED ISSUE #57: Direct Messages repeat
Commit 4c4c480 introduced a change that causes direct messages to be fetched from the discord server multiple times. Looks like a fix would entail either setting those messages as read on the discord server or not refetching them.

### PR DESCRIPTION
**Pull request by bobbybee**
This PR closes #57 

Note: this has not been extensively battletested due to lack of ~~guinea pigs~~ online users. But.. it compiles? :wink:

### CODE REVIEW

File: libdiscord.c [hunk 1]
```diff
@@ -2196,6 +2205,7 @@ discord_build_groups_from_blist(DiscordAccount *ya)
 			discord_id = purple_blist_node_get_string(node, "discord_id");
 			if (discord_id != NULL) {
 				g_hash_table_replace(ya->one_to_ones, g_strdup(discord_id), g_strdup(name));
+				g_hash_table_replace(ya->last_message_id_dm, g_strdup(discord_id), "0");
```
Comment (EionRobb) [inline libdiscord.c]: Don't put a `const char *` (the `"0"`) into a hash table when you've specified the value destroy function is `g_free` (in your `g_hash_table_new_full` init)
